### PR TITLE
Page routing

### PR DESCRIPTION
**Pull request by foolhardy21**
## Client Side Routes

This PR has the routes and links for all the pages.

- Files to review:
   - [ ] src/App.js
   - [ ] src/components/Cart/CartHeader.js
   - [ ] src/components/Home/HomeHeader.js
   - [ ] src/components/Login/LoginHeader.js
   - [ ] src/components/Products/ProductsHeader.js
   - [ ] src/components/Signup/SignupHeader.js
   - [ ] src/components/Signup/SignupCard.js
   - [ ] src/components/Wishlist/WishListHeader.js

- Ignore any other files for now.

- Use this link for preview - https://deploy-preview-7--pensive-perlman-311072.netlify.app/

Thanks.

### CODE REVIEW

**Comment by yash9263** [comment]
Code looks good and clean good use of custom hooks and utils functions.
The commit history is a little bloated try to use `git pull <remoteName> <branchName> --rebase` and `git commit --amend` 
and git effectively to keep your commits history clean and clear. Use some tools like `prettier` to format your code properly.

**Review by yash9263 — APPROVED** [review]

**Comment by foolhardy21** [comment]
> Code looks good and clean good use of custom hooks and utils functions. The commit history is a little bloated try to use `git pull <remoteName> <branchName> --rebase` and `git commit --amend` and git effectively to keep your commits history clean and clear. Use some tools like `prettier` to format your code properly.

thanks @yash9263 for the feedback. Will incorporate these practices.

**Review by jalajcodes — APPROVED** [review]
checked the files you mentioned above. Everything looks good.

p.s. Just try to make small pr's from next time😅

**Comment by foolhardy21** [comment]
> checked the files you mentioned above. Everything looks good.
> 
> p.s. Just try to make small pr's from next time😅

thanks. the actual code to be reviewed was only routes. the lines of code shown is because of rebasing.

**Pull request merged**
